# Generated by Django 5.0.2 on 2024-04-07 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_alter_talks_dislike_alter_talks_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='talks',
            old_name='dislike',
            new_name='dislikes',
        ),
    ]
