# Generated by Django 5.0.2 on 2024-04-07 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_rename_dislike_talks_dislikes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talks',
            name='dislikes',
        ),
    ]
